services:
  # 1. Your Next.js App
  web:
    container_name: jop-portal
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - "3000:3000" # Exposed via Nginx now
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:examplepassword@mongo:27017/jobportal?authSource=admin
      - NEXTAUTH_SECRET=0169e5bd6885899b4a172a503093bd880a5b1baabda56b6562f281d92d510c1c
      - NEXTAUTH_URL=http://localhost:3000
    env_file:
      # Use the special docker env file we will create
      - .env.docker
    volumes:
      - uploads_data:/app/public/uploads # Persist CVs
    depends_on:
      - mongo

  # 1.5 Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: jop-portal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  # 2. Self-Hosted Database
  mongo:
    image: mongo:6.0
    container_name: jop-portal-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo_data:/data/db # Persist Database Data

# Define the Named Volumes (Docker manages these storage areas)
volumes:
  mongo_data:
  uploads_data:
